#!/usr/bin/env python3
"""
build_visual_index.py -- Generate 00_VISUAL_INDEX.html and .md so that anyone
opening this package sees REAL ULTRASOUND on the first screen, not a directory
listing.

V1's failure mode was a package that read as folders of Markdown and bar charts.
The index exists to make the evidence immediately visible and to state, next to
every thumbnail, what the pixels actually are and what they are not.
"""
from __future__ import annotations
import argparse
import csv
import html
import json
import pathlib

ROOT = pathlib.Path(".")
VIS = pathlib.Path("visuals/ultrasound/real_human_lumbar")

SECTIONS = [
    ("Expert-annotated real human lumbar ultrasound", "side_by_side",
     "Raw frame | physician expert bone-surface annotation | overlay. "
     "Real human in-vivo transcutaneous lumbar ultrasound.", 8),
    ("Model predictions on held-out subjects", "prediction_overlays",
     "raw | expert label | our prediction | TP/FN/FP error | MC-dropout uncertainty. "
     "Every subject shown was held OUT of the model predicting on it.", 8),
    ("Failure cases", "failures",
     "The worst-scoring held-out frames. Shown deliberately, not hidden.", 6),
    ("Handheld (HUS)", "hus", "Expert overlay, handheld acquisition.", 6),
    ("Robot-assisted (RUS)", "rus", "Expert overlay, robot-assisted acquisition.", 6),
    ("Difficult cases", "difficult_cases",
     "Smallest annotations, and frames the expert left EMPTY (no identifiable bone surface).", 6),
    ("Contact sheets", "contact_sheets",
     "Dense grids for rapid inspection; each states its own selection rule.", 4),
    ("Publication candidates", "publication_candidates",
     "Composite figures assembled for the paper.", 4),
]

BANNER = ("These are annotations of VISIBLE BONE SURFACE. They are NOT lumbar-puncture "
          "targets, entry points, trajectories or safety windows. No public dataset "
          "contains those.")


def listing(sub, n):
    d = VIS / sub
    if not d.exists():
        return []
    ps = sorted(d.glob("*.png"))
    if len(ps) <= n:
        return ps
    step = max(1, len(ps) // n)
    return ps[::step][:n]


def stats():
    s = {}
    idx = pathlib.Path("data/processed/kuleuven_lumbar/index.csv")
    if idx.exists():
        rows = list(csv.DictReader(open(idx, encoding="utf-8")))
        s["frames"] = len(rows)
        s["subjects"] = len({r["subject"] for r in rows})
        s["hus"] = sum(1 for r in rows if r["modality"] == "HUS")
        s["rus"] = sum(1 for r in rows if r["modality"] == "RUS")
        s["empty"] = sum(1 for r in rows if r["empty_label"] == "True")
    res = pathlib.Path("experiments/exp005_lumbar_bone_seg/results.json")
    if res.exists():
        r = json.loads(res.read_text(encoding="utf-8"))
        both = [x for x in r if x["train_regime"] == "BOTH"]
        if both:
            s["best_dice"] = max(x["subject_mean_dice"] for x in both)
            s["n_runs"] = len(r)
    return s


def main():
    ap = argparse.ArgumentParser()
    a = ap.parse_args()
    st = stats()
    hdr = (f"{st.get('frames','?')} expert-annotated frames · "
           f"{st.get('subjects','?')} human subjects · "
           f"{st.get('hus','?')} handheld / {st.get('rus','?')} robot-assisted")

    # ---------------- HTML ----------------
    h = ["<!-- generated by tools/build_visual_index.py -->",
         "<style>",
         "body{background:#131313;color:#e8e8e8;font:14px/1.55 system-ui,sans-serif;margin:0;padding:28px;}",
         "h1{font-size:26px;margin:0 0 6px;} h2{font-size:18px;margin:34px 0 4px;border-bottom:1px solid #333;padding-bottom:6px;}",
         "p.sub{color:#9a9a9a;margin:0 0 4px;} .banner{background:#3a1d1d;border:1px solid #7a3535;padding:12px 14px;border-radius:8px;margin:16px 0 8px;color:#ffd9d9;}",
         ".grid{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px;}",
         ".card{background:#1c1c1c;border:1px solid #2e2e2e;border-radius:8px;padding:7px;max-width:330px;}",
         ".card img{max-width:320px;display:block;border-radius:4px;}",
         ".card div{color:#8f8f8f;font-size:11px;margin-top:5px;word-break:break-all;}",
         "code{background:#222;padding:1px 5px;border-radius:4px;}",
         "</style>",
         "<h1>Real human lumbar ultrasound — visual evidence</h1>",
         f"<p class='sub'>{html.escape(hdr)}</p>",
         "<p class='sub'>Source: KU Leuven / Balgrist, "
         "<code>doi:10.48804/3XPCAE</code>, CC-BY-4.0. "
         "Cavalcanti et al., <code>doi:10.1038/s41597-025-06047-9</code>.</p>",
         f"<div class='banner'><b>Read this first.</b> {html.escape(BANNER)}</div>"]

    m = ["<!-- generated by tools/build_visual_index.py -->",
         "# Real human lumbar ultrasound — visual evidence", "",
         f"**{hdr}**", "",
         "Source: KU Leuven / Balgrist, `doi:10.48804/3XPCAE`, CC-BY-4.0 "
         "(Cavalcanti et al., `doi:10.1038/s41597-025-06047-9`).", "",
         f"> **Read this first.** {BANNER}", ""]

    for title, sub, desc, n in SECTIONS:
        ps = listing(sub, n)
        total = len(list((VIS / sub).glob("*.png"))) if (VIS / sub).exists() else 0
        h += [f"<h2>{html.escape(title)} <span style='color:#777;font-size:13px'>({total} assets)</span></h2>",
              f"<p class='sub'>{html.escape(desc)}</p>", "<div class='grid'>"]
        m += [f"## {title}  ({total} assets)", "", desc, ""]
        for p in ps:
            rel = p.as_posix()
            h += [f"<div class='card'><a href='{rel}'><img src='{rel}' loading='lazy'></a>"
                  f"<div>{html.escape(p.name)}</div></div>"]
            m += [f"[![{p.name}]({rel})]({rel})"]
        h += ["</div>"]
        m += [""]

    h += ["<h2>Where the numbers are</h2><p class='sub'>",
          "<code>RESULTS_LEDGER.csv</code> · <code>CLAIMS_LEDGER.csv</code> · ",
          "<code>experiments/exp005_lumbar_bone_seg/results.json</code> · ",
          "<code>visuals/ultrasound/real_human_lumbar/ANNOTATION_PROVENANCE.csv</code> · ",
          "<code>PIXEL_LICENSE_LEDGER.csv</code></p>"]
    m += ["## Where the numbers are", "",
          "- `RESULTS_LEDGER.csv`, `CLAIMS_LEDGER.csv`",
          "- `experiments/exp005_lumbar_bone_seg/results.json`",
          "- `visuals/ultrasound/real_human_lumbar/ANNOTATION_PROVENANCE.csv`",
          "- `PIXEL_LICENSE_LEDGER.csv`", ""]

    pathlib.Path("00_VISUAL_INDEX.html").write_text("\n".join(h), encoding="utf-8")
    pathlib.Path("00_VISUAL_INDEX.md").write_text("\n".join(m), encoding="utf-8")
    print("wrote 00_VISUAL_INDEX.html and 00_VISUAL_INDEX.md")
    for title, sub, _, _ in SECTIONS:
        n = len(list((VIS / sub).glob("*.png"))) if (VIS / sub).exists() else 0
        print(f"   {sub:24s} {n}")


if __name__ == "__main__":
    main()
